# Generated by Django 2.2.12 on 2021-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=11, verbose_name='姓名'),
        ),
    ]
