# Generated by Django 2.2.12 on 2021-05-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210522_1111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
