# Generated by Django 2.2.12 on 2021-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20210522_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.CharField(default='', max_length=10, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='价格'),
        ),
    ]
