# Generated by Django 2.2.12 on 2021-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
    ]
