# Generated by Django 2.2.12 on 2021-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20210526_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
