# Generated by Django 2.2.12 on 2021-05-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20210526_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者档案', 'verbose_name_plural': '作者档案'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '我的图书馆', 'verbose_name_plural': '我的图书馆'},
        ),
    ]
